name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Clean dependencies  # 🛠 NEW STEP
      run: rm -rf node_modules package-lock.json

    - name: Install dependencies
      run: npm install  # Change from 'npm ci' to 'npm install'

    - name: Run tests
      run: npm test
